test_that("InMemoryStorage creates study and returns id", {
  s <- InMemoryStorage$new()
  id <- s$create_study("my_study", "minimize")
  expect_equal(id, 1L)
  info <- s$get_study(id)
  expect_equal(info$study_name, "my_study")
  expect_equal(info$direction, "minimize")
})

test_that("InMemoryStorage creates trials with incrementing numbers", {
  s <- InMemoryStorage$new()
  sid <- s$create_study("s", "minimize")
  t1 <- s$create_trial(sid)
  t2 <- s$create_trial(sid)
  expect_equal(t1, 1L)
  expect_equal(t2, 2L)
  snap <- s$get_trial(sid, t1)
  expect_equal(snap$number, 0L)
  snap2 <- s$get_trial(sid, t2)
  expect_equal(snap2$number, 1L)
})

test_that("InMemoryStorage set_trial_state marks complete with value", {
  s <- InMemoryStorage$new()
  sid <- s$create_study("s", "minimize")
  tid <- s$create_trial(sid)
  s$set_trial_state(sid, tid, "complete", value = 0.5)
  snap <- s$get_trial(sid, tid)
  expect_equal(snap$state, "complete")
  expect_equal(snap$value, 0.5)
})

test_that("InMemoryStorage stores params and distributions", {
  s <- InMemoryStorage$new()
  sid <- s$create_study("s", "minimize")
  tid <- s$create_trial(sid)
  d <- float_distribution(0, 1)
  s$set_trial_param(sid, tid, "lr", d, 0.01)
  snap <- s$get_trial(sid, tid)
  expect_equal(snap$params$lr, 0.01)
  expect_s3_class(snap$distributions$lr, "roptuna_float_distribution")
})

test_that("get_all_trials filters by state", {
  s <- InMemoryStorage$new()
  sid <- s$create_study("s", "minimize")
  t1 <- s$create_trial(sid)
  t2 <- s$create_trial(sid)
  s$set_trial_state(sid, t1, "complete", value = 1.0)
  s$set_trial_state(sid, t2, "pruned")
  all <- s$get_all_trials(sid)
  expect_equal(length(all), 2)
  complete <- s$get_all_trials(sid, states = "complete")
  expect_equal(length(complete), 1)
  expect_equal(complete[[1]]$value, 1.0)
})

test_that("InMemoryStorage stores intermediate values", {
  s <- InMemoryStorage$new()
  sid <- s$create_study("s", "minimize")
  tid <- s$create_trial(sid)
  s$set_trial_intermediate_value(sid, tid, step = 1L, value = 0.8)
  s$set_trial_intermediate_value(sid, tid, step = 2L, value = 0.6)
  snap <- s$get_trial(sid, tid)
  expect_equal(snap$intermediate_values[["1"]], 0.8)
  expect_equal(snap$intermediate_values[["2"]], 0.6)
})
